package
{
	import com.bit101.components.*;
	import flash.display.*;
	import flash.net.*;
	import flash.events.*;
	/*
	 * HTMLWebCreator v0.1
	 * Copyright (c) <2011> <Bruce Jawn> [http://bruce-lab.blogspot.com]
	 * This software is released under the MIT License
	 * <http://www.opensource.org/licenses/mit-license.php>
	 * Todo: Import HTML
	 * HTML Source Template by [Play.FLASWF.TK], released under public domain.
	 */
	public class HTMLWebCreator extends Sprite
	{
		//HTML Source Template
		private var HTML_SOURCE:String = (<![CDATA[<!DOCTYPE html>
<html>
<!-- ############################### -->
<!-- HTML generated by Bruce's HTMLWebCreator v0.1 -->
<!-- HTML template by [Play.FLASWF.TK] -->
<!-- ############################### -->
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>$_YourGameTitle_$</title>
  </head>
  <body>

<!-- This is a comment - body begins -->
<!-- ############################### -->
<!-- ############################### -->

<!-- ########## Embed SWF ########## -->
<center>
<a href="http://play.flaswf.tk/" target="_blank">Go Back</a><br>
<embed src="$_YourSWFEmbedURL_$" quality="$_YourSWFQuality_$" bgcolor="#$_YourSWFBgcolor_$" width="$_YourSWFWidth_$" height="$_YourSWFHeight_$" 
wmode="$_YourSWFWmode_$" allowFullScreen="$_YourSWFallowFullScreen_$" allowScriptAccess="$_YourSWFallowScriptAccess_$" allowNetworking="$_YourSWFallowNetworking_$" 
type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer" />
<br><a href="http://adf.ly/821527/$_YourSWFDownloadURL_$" target="_blank">Download Game!</a><br>
</center>
<!-- ########## Embed SWF ########## -->

<!-- ########## Introduction ####### -->
<p>
[Introduction]<br>
$_YourGameIntroduction_$
</p>
<!-- ########## Introduction ####### -->

<!-- ########## Controls ########### -->
<p>
[Controls]<br>
$_YourGameControls_$
</p>
<!-- ########## Controls ########### -->

<!-- ########## Other Infos ######## -->
<p>
[About]<br>
$_YourGameAbout_$
</p>
<!-- ########## Other Infos ######## -->

<!-- ############################### -->
<!-- ############################### -->
<!-- This is a comment - body ends -->

  </body>
</html>]]>).toString();
	//end of HTML Source Template
	
		private var GameName_L:Label;
		private var GameName_IT:InputText;
		
		private var Width_L:Label;
		private var Width_IT:InputText;
		
		private var Height_L:Label;
		private var Height_IT:InputText;
		
		private var EmbedURL_L:Label;
		private var EmbedURL_IT:InputText;
		
		private var DownloadURL_L:Label;
		private var DownloadURL_IT:InputText;
		
		private var SWFBgcolor_L:Label;
		private var SWFBgcolor_IT:InputText;
		
		private var SWFQuality_L:Label;
		private var SWFQuality_CB:ComboBox;
		
		private var SWFwmode_L:Label;
		private var SWFwmode_CB:ComboBox;
		
		private var SWFallowFullScreen_L:Label;
		private var SWFallowFullScreen_CB:ComboBox;
		
		private var SWFallowScriptAccess_L:Label;
		private var SWFallowScriptAccess_CB:ComboBox;
		
		private var SWFallowNetworking_L:Label;
		private var SWFallowNetworking_CB:ComboBox;
		
		private var Introduction_L:Label;
		private var Introduction_IT:TextArea;
		
		private var Controls_L:Label;
		private var Controls_IT:TextArea;
		
		private var About_L:Label;
		private var About_IT:TextArea;
		
		private var Save_PB:PushButton;
		
		public function HTMLWebCreator()
		{
			GameName_L = new Label(this, 50, 30, "Game Name");
			GameName_IT = new InputText(this, 150, 30, "Game Title");
			
			Width_L = new Label(this, 300, 30, "Width");
			Width_IT = new InputText(this, 400, 30, "640");
			
			Height_L = new Label(this, 550, 30, "Height");
			Height_IT = new InputText(this, 650, 30, "480");
			
			EmbedURL_L = new Label(this, 50, 60, "Embed URL");
			EmbedURL_IT = new InputText(this, 150, 60, "http://");
			EmbedURL_IT.width = 350;
			
			DownloadURL_L = new Label(this, 50, 90, "Download URL");
			DownloadURL_IT = new InputText(this, 150, 90, "http://");
			DownloadURL_IT.width = 350;
			
			SWFBgcolor_L = new Label(this, 50, 120, "Bground color");
			SWFBgcolor_IT = new InputText(this, 150, 120, "000000");
			SWFBgcolor_IT.textField.addEventListener(Event.CHANGE, function(event:Event):void
				{
					SWFBgcolor_IT.textField.textColor = int("0x" + SWFBgcolor_IT.text)
				});
			//http://helpx.adobe.com/flash/kb/flash-object-embed-tag-attributes.html
			SWFQuality_L = new Label(this, 300, 120, "Quality");
			SWFQuality_CB = new ComboBox(this, 400, 120, "SWFQuality");
			SWFQuality_CB.addItem("low");
			SWFQuality_CB.addItem("medium");
			SWFQuality_CB.addItem("high");
			SWFQuality_CB.addItem("autolow");
			SWFQuality_CB.addItem("autohigh");
			SWFQuality_CB.addItem("best");
			SWFQuality_CB.selectedItem = "high";
			
			SWFwmode_L = new Label(this, 550, 120, "Wmode");
			SWFwmode_CB = new ComboBox(this, 650, 120, "SWF Wmode");
			SWFwmode_CB.addItem("window");
			SWFwmode_CB.addItem("opaque");
			SWFwmode_CB.addItem("transparent");
			SWFwmode_CB.addItem("direct");
			SWFwmode_CB.addItem("gpu");
			SWFwmode_CB.selectedItem = "window";
			
			SWFallowFullScreen_L = new Label(this, 50, 150, "FullScreen");
			SWFallowFullScreen_CB = new ComboBox(this, 150, 150, "SWFQuality");
			SWFallowFullScreen_CB.addItem("true");
			SWFallowFullScreen_CB.addItem("false");
			SWFallowFullScreen_CB.selectedItem = "true";
			
			SWFallowScriptAccess_L = new Label(this, 300, 150, "ScriptAccess");
			SWFallowScriptAccess_CB = new ComboBox(this, 400, 150, "SWFallowScriptAccess");
			SWFallowScriptAccess_CB.addItem("always");
			SWFallowScriptAccess_CB.addItem("never");
			SWFallowScriptAccess_CB.addItem("samedomain");
			SWFallowScriptAccess_CB.selectedItem = "samedomain";
			
			SWFallowNetworking_L = new Label(this, 550, 150, "Networking");
			SWFallowNetworking_CB = new ComboBox(this, 650, 150, "SWFallowNetworking");
			SWFallowNetworking_CB.addItem("all");
			SWFallowNetworking_CB.addItem("internal");
			SWFallowNetworking_CB.addItem("none");
			SWFallowNetworking_CB.selectedItem = "all";
			
			Introduction_L = new Label(this, 360, 185, "Introduction");
			Introduction_IT = new TextArea(this, 50, 210, '<blockquote>"9/10!A very good game."</blockquote>\r<cite>play.flaswf.tk</cite>\r<!-- This is a comment - You can use HTML code here -->\r<!-- Return Key for new lines, the new line tag <br> will be inserted automatically. -->');
			Introduction_IT.width = 700;
			Introduction_IT.height = 100;
			
			Controls_L = new Label(this, 370, 315, "Controls");
			Controls_IT = new TextArea(this, 50, 340, "<b>ArrowKey:</b> <i>Move</i>\r<u>MouseClick:</u> <i>Shoot</i>\r<!-- This is a comment - You can use HTML code here -->");
			Controls_IT.width = 700;
			Controls_IT.height = 100;
			
			About_L = new Label(this, 375, 445, "About");
			About_IT = new TextArea(this, 50, 470, 'Developer: Somebody\rLinks: <a href="http://adf.ly/821527/http://someurl.com/" target="_blank">http://someurl.com/</a>\r<!-- This is a comment - You can use HTML code here -->');
			About_IT.width = 700;
			About_IT.height = 100;
			
			Save_PB = new PushButton(this, 600, 70, "Save HTML!", Save_PB_H);
		}
		
		//http://actionscriptsnips.blogspot.sg/2009/07/search-and-replace.html
		private function strReplace(str:String, search:String, replace:String):String
		{
			return str.split(search).join(replace);
		}
		
		protected function Save_PB_H(event:Event):void
		{
			var HTML_SOURCE_Temp:String = HTML_SOURCE;
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourGameTitle_$", GameName_IT.text);
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFEmbedURL_$", EmbedURL_IT.text);
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFDownloadURL_$", DownloadURL_IT.text);
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFQuality_$", String(SWFQuality_CB.selectedItem));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFBgcolor_$", SWFBgcolor_IT.text);
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFWidth_$", Width_IT.text);
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFHeight_$", Height_IT.text);
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFWmode_$", String(SWFwmode_CB.selectedItem));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFallowFullScreen_$", String(SWFallowFullScreen_CB.selectedItem));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFallowScriptAccess_$", String(SWFallowScriptAccess_CB.selectedItem));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourSWFallowNetworking_$", String(SWFallowNetworking_CB.selectedItem));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourGameIntroduction_$", strReplace(Introduction_IT.text, "\r", "<br>"));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourGameControls_$", strReplace(Controls_IT.text, "\r", "<br>"));
			HTML_SOURCE_Temp = strReplace(HTML_SOURCE_Temp, "$_YourGameAbout_$", strReplace(About_IT.text, "\r", "<br>"));
			
			new FileReference().save(HTML_SOURCE_Temp, strReplace(GameName_IT.text, " ", "") + ".html")
			trace("Save_PB_H");
		}
		
		private function importHTML(htmlSource:String):void
		{
		}
	
	} //end of class
} //end of package
